### ISSUE TITLE
Tutorials documentation needs to be compatible with the newest API

### ISSUE THREAD

**Issue by SongshGeo** [ABSESpy/ABSESpy#43]
now I have other issues (maybe they should be raised in a new issue?):
- running `model.py` returns an error:  `NameError: name 'Human' is not defined` from the line `model=MainModel(human_class=Human, nature_class=Nature)` I seem to be able to fix that by changing the line to `model=MainModel(human_class=CustomHuman, nature_class=CustomNature)`
- when I try to run the [Forest Fire](https://absespy.github.io/ABSESpy/tutorial/beginner/fire_tutorial/) test I get the error `ModuleNotFoundError: No module named 'tests'`

_Originally posted by @jamesdamillington in https://github.com/ABSESpy/ABSESpy/issues/37#issuecomment-2007876913_

**Comment by SongshGeo** [comment]
@jamesdamillington 
It seems that there is some incompatibility between the documentation & tutorials and the newest API. I create this new issue and I'm going to go through them in a day.

**Comment by jamesdamillington** [comment]
@SongshGeo Documentation seems to align better now, thanks. As noted elsewhere, I have now been able to install with python 3.9.18

Mentioning [joss-review](https://github.com/openjournals/joss-reviews/issues/6298) for tracking

**Comment by SongshGeo** [comment]
@jamesdamillington Great! Always at service to improve the package!
