### ISSUE TITLE
docs: software names in joss paper

### ISSUE THREAD

**Issue by wang-boyu** [ABSESpy/ABSESpy#46]
This is part of the [joss review process](https://github.com/openjournals/joss-reviews/issues/6298).

I've noticed a few capitalization issues with some software names in the joss paper, as listed below:

- L105 & L151: netlogo and Netlogo should be NetLogo
- L42, L98, L101 & L153 : mesa-geo and Mesa-geo should be Mesa-Geo
- L95, L97, L98, L102, L129 & L153 : mesa should be Mesa
- L96: abce should be ABCE
- L128, L148 & L154: python should be Python

**Comment by SongshGeo** [comment]
@wang-boyu  Hi, Boyu; thanks for the corrections! I went through the names and corrected them in PR #49.

**Comment by wang-boyu** [comment]
Thanks! The names look correct in the text. However, you might still need to fix those in the references section (sorry):

- L135 & L163 `mesa` --> `Mesa`
- L161 `Netlogo` --> `NetLogo`
- L163 `Mesa-geo` --> `Mesa-Geo`

I think these came from the `refs.bib` file. In this file, you might need to wrap these names with curly braces to preserve capitalization. Otherwise bibtex seems to do some case conversion automatically (see https://tex.stackexchange.com/a/10775).

**Comment by SongshGeo** [comment]
I got the idea and updated the `ref.bib` in #53 and #52. 
Thanks for the reminder!

**Comment by wang-boyu** [comment]
Thanks!
